FROM prom/prometheus:latest

COPY monitoring/prometheus.yml /etc/prometheus/prometheus.yml

EXPOSE 9090

CMD ["--config.file=/etc/prometheus/prometheus.yml", "--storage.tsdb.retention.time=1h", "--storage.tsdb.path=/tmp/prometheus"]
