const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

// Generate RSA keys
const { generateKeyPairSync } = require('crypto');

console.log('Generating RS256 key pair...');

const { privateKey, publicKey } = generateKeyPairSync('rsa', {
  modulusLength: 2048,
  publicKeyEncoding: { type: 'spki', format: 'pem' },
  privateKeyEncoding: { type: 'pkcs8', format: 'pem' }
});

// Generate TOTP encryption key
const totpKey = crypto.randomBytes(32).toString('base64');

// Base64 encode for .env
const privateB64 = Buffer.from(privateKey).toString('base64');
const publicB64 = Buffer.from(publicKey).toString('base64');

// Read existing .env
const envPath = path.join(__dirname, '..', '.env');
let envContent = '';

if (fs.existsSync(envPath)) {
  envContent = fs.readFileSync(envPath, 'utf8');
} else {
  console.log('Creating new .env file...');
}

// Remove old keys if they exist
envContent = envContent
  .split('\n')
  .filter(line => !line.startsWith('JWT_PRIVATE_KEY=') &&
                  !line.startsWith('JWT_PUBLIC_KEY=') &&
                  !line.startsWith('TOTP_ENCRYPTION_KEY='))
  .join('\n');

// Append new keys
const newKeys = `
# Auto-generated by scripts/generate-keys.js
JWT_PRIVATE_KEY=${privateB64}
JWT_PUBLIC_KEY=${publicB64}
TOTP_ENCRYPTION_KEY=${totpKey}
`;

envContent = envContent.trim() + '\n' + newKeys;

// Write back
fs.writeFileSync(envPath, envContent.trim() + '\n');

console.log('✅ Keys generated and saved to .env');
console.log('📁 File:', envPath);
console.log('');
console.log('🔑 Public Key (first 50 chars):', publicB64.substring(0, 50) + '...');
